const TokenType = {
    If: 'If',
    Else: 'Else',
    Let: 'Let',
    Make: 'Make',
    Show: 'Show',
    Loop: 'Loop',
    OpenParen: 'OpenParen',
    CloseParen: 'CloseParen',
    OpenBrace: 'OpenBrace',
    CloseBrace: 'CloseBrace',
    OpenBracket: 'OpenBracket',
    CloseBracket: 'CloseBracket',
    Equals: 'Equals',
    Identifier: 'Identifier',
    Number: 'Number',
    String: 'String',
    Semicolon: 'Semicolon',
    BinaryOperator: 'BinaryOperator',
    Func: 'Func',
    Return: 'Return',
    Comma: 'Comma',
    Boolean: 'Boolean',
    DeleteVar: 'DeleteVar',
};

export default TokenType;
